//
// BathyScaphe
// Preference Default Values List
// For Starlight Breaker
//

// AppDefaults
#define kPreferencesDefault_OnlineMode		YES
#define DEFAULT_IS_BROWSER_VERTICAL			NO
#define DEFAULT_CONTENTS_SEARCH_OPTION		CMRSearchOptionCaseInsensitive
#define DEFAULT_SEARCH_PANEL_EXPANDED		YES
#define DEFAULT_BROWSER_SORT_ASCENDING		YES
#define DEFAULT_BROWSER_STATUS_FILTERINGMAS	0
#define DEFAULT_MAX_FOR_THREADS_HISTORY		20
#define DEFAULT_MAX_FOR_BOARDS_HISTORY		10
#define DEFAULT_MAX_FOR_SEARCH_HISTORY		10
#define DEFAULT_INFORM_WHEN_DAT_OCHI		YES
#define DEFAULT_OLD_SCROLLING				NO
#define DEFAULT_USE_BINARY_FORMAT			NO

// FontsAndColor
#define DEFAULT_MESSAGE_ANCHOR_HAS_UNDERLINE	YES
#define DEFAULT_PARAGRAPH_INDENT				40.0f
#define DEFAULT_REPLY_FONTSIZE					12.0f
#define DEFAULT_IS_RESPOPUP_TEXT_COLOR			NO
#define DEFAULT_POPUP_SCROLLER_SMALL			YES
#define DEFAULT_TV_IDX_SPACING_BEFORE			15.0f
#define DEFAULT_TV_IDX_SPACING_AFTER			10.0f
#define DEFAULT_THREAD_LIST_ROW_HEIGHT			16.0f
#define DEFAULT_THREAD_LIST_DRAWSGRID			NO
#define DEFAULT_THREADS_LIST_FONTSIZE			11.0f
#define DEFAULT_BOARD_LIST_ROW_HEIGHT			19.0f
#define DEFAULT_BOARD_LIST_FONTSIZE				11.0f
#define DEFAULT_SHOULD_THREAD_ANTIALIAS			YES
#define DEFAULT_THREADS_VIEW_FONTSIZE			12.0f
#define DEFAULT_HOST_FONTSIZE					10.0f
#define DEFAULT_BEPROFILELINK_FONTSIZE			10.0f
#define OLD_DEFAULT_MESSAGE_NAME_COLOR			[NSColor colorWithCalibratedRed: 0.0f green: 0.56f blue: 0.0f alpha: 1.0f]
#define OLD_DEFAULT_MESSAGE_TITLE_COLOR			[NSColor colorWithCalibratedRed: 0.56f green: 0.0f blue: 0.0f alpha: 1.0f]

// ThreadViewer
#define kPreferencesDefault_MailAttachmentShown	YES
#define kPreferencesDefault_MailAddressShown	YES
#define DEFAULT_THREAD_VIEWER_LINK_TYPE			ThreadViewerResPopUpLinkType
#define DEFAULT_TV_MAILTO_LINK_TYPE				ThreadViewerResPopUpLinkType
#define DEFAULT_SHOWS_POOF_ON_ABONE				YES
#define DEFAULT_TV_FIRST_VISIBLE				1
#define DEFAULT_TV_LAST_VISIBLE					50
#define DEFAULT_TV_PREVIEW_WITH_NO_MODIFIER		YES
#define DEFAULT_TV_MOUSEDOWN_TIME				0.5
#define DEFAULT_TV_SCROLL_TO_NEW				NO
#define DEFAULT_OPEN_IN_BROWSER_TYPE			0

// Accounts
#define DEFAULT_LOGIN_MARU_IF_NEEDED	YES
#define DEFAULT_LOGIN_BE_ANY_TIME		NO
#define DEFAULT_USE_KEYCHAIN			NO

// Bundle
#define DEFAULT_HELPER_APP			@"CMLogBuccaneer.app"
#define DEFAULT_BW_BBSMENU_URL		@"http://azlucky.s25.xrea.com/2chboard/bbsmenu2.html"
#define DEFAULT_BW_AUTOSYNC			NO
#define DEFAULT_BW_SYNC_INTERVAL	BSAutoSyncByWeek

// Filter
#define DEFAULT_SPAMFILTER_ENABLED			YES
#define DEFAULT_SPAMFILTER_USE_MSG_CORPUS	NO
#define DEFAULT_SPAMFILTER_BEHAVIOR			kSpamFilterLocalAbonedBehavior
#define DEFAULT_AAD_ENABLED					YES

// ThreadsList
#define DEFAULT_TLSEL_HOLDING_MASK			CMRAutoscrollNone
#define DEFAULT_TL_INCREMENTAL_SEARCH		YES
#define DEFAULT_TITLERULER_TEXT_BLACK		NO
#define DEFAULT_TL_AUTORELOAD_WHEN_WAKE		NO
#define DEFAULT_HEADCHECK_INTERVAL			300.0
#define DEFAULT_TL_VIEW_MODE				BSThreadsListShowsLiveThreads

// Background
#define DEFAULT_STABLE_DRAWS_STRIPED	NO
#define DEFAULT_BOARD_LIST_BG_COLOR		[NSColor colorWithCalibratedRed:(231.0/255.0) green:(237.0/255.0) blue:(248.0/255.0) alpha:1.0]
#define DEFAULT_POPUP_BG_COLOR			[NSColor colorWithCalibratedHue : 0.14f saturation : 0.2f brightness : 1.0f alpha : 1.0f]
#define DEFAULT_POPUP_BG_ALPHA			0.85
#define DEFAULT_REPLY_BG_ALPHA			1.0

// Sounds
#define DEFAULT_SOUND_HEADCHECK_NEW		@"Ping"
#define DEFAULT_SOUND_HEADCHECK_NONE	@"Basso"
#define DEFAULT_SOUND_HEADCHECK_REPLY	@""
